stretch_arm:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
  position_only_ik: True
stretch_head:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
<<<<<<< HEAD
  kinematics_solver_timeout: 0.1
=======
  kinematics_solver_timeout: 0.1
armgrip:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
>>>>>>> faeb1127aed2afb4383f7f8d8217cb5122d15116
