base_local_planner: "dwa_local_planner/DWAPlannerROS"

DWAPlannerROS:
  #vel params
  max_vel_x: 0.25
  min_vel_x: 0
  max_vel_y: 0
  min_vel_y: 0
  max_vel_trans: 1.0
  min_vel_trans: 0
  max_vel_theta: 0.25
  min_vel_theta: 0

  #accel params
  acc_lim_x: 1.0
  acc_lim_th: 1.0
  acc_lim_y: 0

  #forward sim params
  sim_time: 1.1
  vx_samples: 3 #was 5
  vy_samples: 0 #diff drive
  vth_samples: 15

  #scoring params
  path_distance_bias: 32
  goal_distance_bias: 24
  occdist_scale: 0.1
  forward_point_distance: 0.3

  #higher goal tolerance
  yaw_goal_tolerance: 0.1
  xy_goal_tolerance: 0.25
  latch_xy_goal_tolerance: true

  #lower goal tolerance
  #yaw_goal_tolerance: 0.05
  #xy_goal_tolerance: 0.1
  #latch_xy_goal_tolerance: false

  prune_plan: true
